#!/bin/bash

export DEKART_PORT=8080
export DEKART_STATIC_FILES=./build
export DEKART_POSTGRES_DB=dekart
export DEKART_POSTGRES_USER=dekart
export DEKART_POSTGRES_PASSWORD=dekart
export DEKART_POSTGRES_PORT=5432
export DEKART_POSTGRES_HOST=localhost
export DEKART_MAPBOX_TOKEN=pk.eyJ1IjoiZGVsZnJyciIsImEiOiJja2l6MXZqdjgxaXFjMnNtZTgzaHhsMGM5In0.ifCwBcTR2U-jgDev22PaSw
export DEKART_STORAGE=SNOWFLAKE
export DEKART_DATASOURCE=SNOWFLAKE
export DEKART_LOG_DEBUG=1
export DEKART_CORS_ORIGIN=null
export DEKART_STREAM_TIMEOUT=10

cd /dekart

/dekart/server