/* global cy, describe, it, Cypress, expect */

// Exercise real uploads and server persistence through the normal report editor.
describe('Integrated report widgets', { scrollBehavior: 'center' }, () => {
  it('creates widgets for an uploaded file, saves settings and reloads the report', () => {
    cy.visit('/')
    cy.get('body', { timeout: 30000 }).should(body => {
      expect(body.find('#dekart-create-report').length || body.text().includes('Ready to connect')).to.be.ok
    }).then(body => {
      if (body.text().includes('Ready to connect')) cy.contains('button', 'Use file upload').click()
      else cy.get('#dekart-create-report').click()
    })
    cy.contains('button', 'Upload File', { timeout: 30000 }).click()
    cy.get('input[type="file"]').selectFile({
      contents: Cypress.Buffer.from('latitude,longitude,operator,capacity_kw\n52.5,13.4,Alpha,100\n52.6,13.5,Alpha,200\n51.5,7.4,Beta,50\n51.6,7.5,Beta,150\n'),
      fileName: 'stations.csv',
      mimeType: 'text/csv'
    }, { force: true })
    cy.contains('button', 'Upload', { matchCase: true }).last().click()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.get('[data-testid="widgets-tab"]').should('not.contain.text', 'filter')
    cy.get('button[aria-label="Open panel settings"]', { timeout: 60000 }).first().click()
    cy.get('[data-testid="widget-settings"] input:not([type="number"])').first().clear().type('Network operators').blur()
    cy.get('#dekart-save-button').click()
    cy.get('#dekart-save-button [aria-label="cloud"]', { timeout: 20000 }).should('be.visible')
    cy.reload()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.contains('Network operators', { timeout: 60000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]').should('not.contain.text', 'filter')
    cy.get('g[aria-label="bar"][data-index="1"] rect', { timeout: 30000 }).first().click()
    cy.contains('button', 'Clear filters', { timeout: 20000 }).should('be.visible')
    cy.get('#dekart-save-button').click()
    cy.get('#dekart-save-button [aria-label="cloud"]', { timeout: 20000 }).should('be.visible')
    cy.reload()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.contains('button', 'Clear filters', { timeout: 20000 }).should('be.visible')
    cy.url().then(url => cy.visit(url.replace('/source', '')))
    cy.contains('button', 'Clear filters', { timeout: 20000 }).should('be.visible')
    cy.contains('button', 'Clear filters').click()
    cy.get('[data-testid="widgets-tab"]').should('not.contain.text', 'filter')
    cy.reload()
    cy.contains('button', 'Clear filters', { timeout: 20000 }).should('be.visible')
    cy.screenshot('integrated-widgets')
    cy.url().then(originalUrl => {
      cy.get('#dekart-fork-button').click()
      cy.url({ timeout: 30000 }).should('not.eq', originalUrl)
    })
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.contains('Network operators', { timeout: 60000 }).should('be.visible')
    cy.get('button[aria-label="Remove dashboard panel"]', { timeout: 60000 }).should('have.length', 2)
    cy.get('button[aria-label="Remove dashboard panel"]').first().click()
    cy.get('button[aria-label="Remove dashboard panel"]').first().click()
    cy.contains('Dashboard is empty').should('be.visible')
    cy.get('[data-testid="widgets-tab"]').should('not.contain.text', 'filter')
    cy.get('[data-testid="widgets-tab"]').should('not.contain.text', 'filter')
    cy.get('#dekart-save-button').click()
    cy.get('#dekart-save-button [aria-label="cloud"]', { timeout: 20000 }).should('be.visible')
    cy.reload()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.contains('Dashboard is empty', { timeout: 60000 }).should('be.visible')
    cy.contains('button', 'Add widget').click()
    cy.contains('button', 'Category').click()
    cy.get('[data-testid="inline-widget-builder"] [role="combobox"]').first().click()
    cy.get('[role="option"]').contains('operator').click()
    cy.contains('button', /^Create$/).click()
    cy.get('g[aria-label="bar"][data-index="1"] rect', { timeout: 30000 }).should('have.length', 2)
    cy.get('#dekart-save-button').click()
    cy.get('#dekart-save-button [aria-label="cloud"]', { timeout: 20000 }).should('be.visible')
    cy.viewport(390, 844)
    cy.contains('button', 'Add widget').should('be.visible')
    cy.get('body').then(body => expect(body[0].scrollWidth).to.be.at.most(390))
    cy.screenshot('widgets-narrow')
  })

  it('builds and refreshes widgets from a real DuckDB query', () => {
    cy.visit('/')
    cy.get('#dekart-create-report', { timeout: 30000 }).click()
    cy.contains('button', 'DuckDB', { timeout: 30000 }).click()
    const enterSQL = rows => {
      cy.get('.ace_editor:visible textarea').click({ force: true }).type('{meta+a}{backspace}', { force: true })
      cy.get('.ace_editor:visible textarea').then($textarea => {
        const view = $textarea[0].ownerDocument.defaultView
        const clipboardData = new view.DataTransfer()
        clipboardData.setData('text/plain', `SELECT 51 + i/100.0 AS latitude, 8 + i/100.0 AS longitude, CASE WHEN i%2=0 THEN 'Solar' ELSE 'Wind' END AS category, i*10 AS capacity_kw FROM range(${rows}) t(i)`)
        $textarea[0].dispatchEvent(new view.ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData }))
      })
      cy.get('#dekart-query-execute-button').should('be.enabled').click()
      cy.get('#dekart-query-status-message', { timeout: 120000 }).should('contain', 'Ready')
    }
    enterSQL(100)
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.get('g[aria-label="text"] text', { timeout: 60000 }).first().should('have.text', '50')
    cy.get('g[aria-label="bar"][data-index="1"] rect', { timeout: 30000 }).should('have.length', 2)
    cy.get('#dekart-report-page-tabs').should('be.visible')
    enterSQL(20)
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.get('g[aria-label="text"] text', { timeout: 60000 }).first().should('have.text', '10')
    cy.get('#dekart-save-button').click()
    cy.get('#dekart-save-button [aria-label="cloud"]', { timeout: 20000 }).should('be.visible')
    cy.reload()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.get('g[aria-label="text"] text', { timeout: 60000 }).first().should('have.text', '10')
    cy.screenshot('query-widgets')
  })

  it('uses a backend Postgres query as a widget dataset', () => {
    const name = `Widget Postgres ${Date.now()}`
    cy.visit('/connections')
    cy.get('body', { timeout: 30000 }).should('contain', 'Connect').then(body => {
      if (body.find('#dekart-new-connection-connections').length) cy.get('#dekart-new-connection-connections').click()
    })
    cy.get('#dekart-connection-type-card-postgres').click()
    cy.get('input#connectionName').clear().type(name)
    cy.get('input#postgresHost').clear().type('localhost')
    cy.get('input#postgresUsername').clear().type('postgres')
    cy.get('input#postgresPassword').clear().type('dekart')
    cy.get('input#postgresDatabase').clear().type('dekart_geo')
    cy.get('input#postgresPort').clear().type(String(Cypress.env('DEKART_POSTGRES_PORT')))
    cy.get('#testConnection').scrollIntoView().click({ scrollBehavior: 'center' })
    cy.get('#saveConnection', { timeout: 30000 }).should('be.enabled').click()
    cy.contains(name, { timeout: 30000 }).should('be.visible')
    cy.visit('/')
    cy.get('#dekart-create-report', { timeout: 30000 }).click()
    cy.contains('button', name, { timeout: 30000 }).click()
    cy.enterQuery("SELECT 51+i/100.0 AS latitude, 8+i/100.0 AS longitude, CASE WHEN i%2=0 THEN 'Solar' ELSE 'Wind' END AS category, i*10 AS capacity_kw FROM generate_series(0,99) AS i")
    cy.get('#dekart-query-execute-button').click()
    cy.get('#dekart-query-status-message', { timeout: 120000 }).should('contain', 'Ready')
    cy.get('[data-testid="widgets-tab"]', { timeout: 30000 }).then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.get('g[aria-label="text"] text', { timeout: 60000 }).first().should('have.text', '50')
    cy.get('g[aria-label="bar"][data-index="1"] rect', { timeout: 30000 }).first().click()
    cy.contains('button', 'Clear filters', { timeout: 20000 }).should('be.visible')
    cy.screenshot('postgres-widgets')
  })
})
