/* global cy, describe, it, Cypress, expect */

// Exercise aggregate semantics on raw rows, then prove linked filtering and backend persistence.
describe('Number charts', () => {
  it('creates metrics, follows category filters, and saves settings with the report', () => {
    cy.visit('/')
    cy.get('body', { timeout: 30000 }).should(body => {
      expect(Boolean(body.find('#dekart-create-report').length || body.text().includes('Ready to connect'))).to.equal(true)
    }).then(body => {
      if (body.text().includes('Ready to connect')) cy.contains('button', 'Use file upload').click()
      else cy.get('#dekart-create-report').click()
    })
    cy.contains('button', 'Upload File', { timeout: 30000 }).click()
    cy.get('input[type="file"]').selectFile({ contents: Cypress.Buffer.from('latitude,longitude,operator,station_id,energy\n52,13,Alpha,A,10\n53,14,Alpha,A,30\n54,15,Beta,B,80\n55,16,Beta,C,\n56,17,Gamma,C,\n'), fileName: 'number-metrics.csv', mimeType: 'text/csv' }, { force: true })
    cy.contains('button', 'Upload', { matchCase: true }).last().click()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]').click()
    cy.contains('button', 'Add chart', { timeout: 120000 }).click()
    cy.contains('button', /^Number/).click()
    cy.contains('button', /^Create$/).click()
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).should('have.text', '5')
    cy.get('button[aria-label="Open panel settings"]').last().click()
    const select = (label, option) => {
      cy.get(`button[aria-label="${label}"]`).click()
      cy.contains('[role="option"]', new RegExp(`^${option}$`)).click()
    }
    select('Operation', 'Sum')
    cy.contains('button', /^Back to charts$/).click()
    cy.contains('Choose a field in chart settings.').should('be.visible')
    cy.get('button[aria-label="Open panel settings"]').last().click()
    cy.contains('[role="combobox"]', 'Select column').click()
    cy.contains('[role="option"]', /^energy/).click()
    cy.get('#widget-title').clear().type('Energy delivered')
    cy.get('input[aria-label="Subtitle"]').type('Selected sessions')
    cy.get('input[aria-label="Suffix"]').type('kWh')
    cy.contains('button', /^Back to charts$/).click()
    cy.get('[data-testid="number-value"]').should('have.text', '120')
    cy.get('[data-testid="number-chart"]').should('contain.text', 'Selected sessions').and('contain.text', 'kWh')
    // The category selected in the map dashboard narrows the metric's source rows.
    cy.get('g[aria-label="bar"][data-index="1"] rect').first().click({ force: true })
    cy.get('[data-testid="number-value"]').should('have.text', '40')
    cy.contains('button', 'Clear all').click()
    cy.get('[data-testid="number-value"]').should('have.text', '120')
    // Null-only groups distinguish an absent metric from a zero-valued metric.
    cy.get('g[aria-label="bar"][data-index="1"] rect').last().click({ force: true })
    cy.get('[data-testid="number-value"]').should('have.text', 'No data')
    cy.contains('button', 'Clear all').click()
    cy.get('[data-testid="number-value"]').should('have.text', '120')
    for (const [operation, expected] of [['Average', '40'], ['Minimum', '10'], ['Maximum', '80'], ['Median', '30'], ['Count rows', '5']]) {
      cy.get('button[aria-label="Open panel settings"]').last().click()
      select('Operation', operation)
      cy.contains('button', /^Back to charts$/).click()
      cy.get('[data-testid="number-value"]').should('have.text', expected)
    }
    cy.get('button[aria-label="Open panel settings"]').last().click()
    select('Operation', 'Count distinct')
    cy.get('[data-testid="widget-settings"] [role="combobox"]').contains('energy').click()
    cy.contains('[role="option"]', /^station_id/).click()
    cy.contains('button', /^Back to charts$/).click()
    cy.get('[data-testid="number-value"]').should('have.text', '3')
    cy.get('button[aria-label="Open panel settings"]').last().click()
    select('Operation', 'Sum')
    cy.get('[data-testid="widget-settings"] [role="combobox"]').contains('station_id').click()
    cy.contains('[role="option"]', /^energy/).click()
    select('Number format', 'Number')
    select('Decimal places', '1')
    cy.contains('button', /^Back to charts$/).click()
    cy.get('[data-testid="number-value"]').should('have.text', '120.0')
    cy.get('#dekart-save-button').click()
    cy.get('#dekart-save-button [aria-label="cloud"]', { timeout: 20000 }).should('be.visible')
    cy.reload()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]').click()
    cy.get('[data-testid="number-value"]', { timeout: 60000 }).should('have.text', '120.0')
    cy.get('[data-testid="number-chart"]').should('contain.text', 'Selected sessions').and('contain.text', 'kWh')
    cy.screenshot('number-chart-saved')
    cy.url().then(url => cy.visit(url.replace('/source', '')))
    cy.get('[data-testid="widgets-tab"]').click()
    cy.get('[data-testid="number-value"]', { timeout: 60000 }).should('have.text', '120.0')
    cy.contains('button', 'Add chart').should('not.exist')
    cy.get('g[aria-label="bar"][data-index="1"] rect').first().click({ force: true })
    cy.get('[data-testid="number-value"]').should('have.text', '40.0')
    cy.reload()
    cy.get('[data-testid="widgets-tab"]').click()
    cy.get('[data-testid="number-value"]', { timeout: 60000 }).should('have.text', '120.0')
  })
})
