/* global cy, describe, it, Cypress, expect */

describe('Report-wide widgets', () => {
  it('shows widgets from two datasets together and chooses sources during creation', () => {
    const upload = (name, column) => {
      cy.contains('button', 'Upload File', { timeout: 30000 }).click()
      cy.get('input[type="file"]').selectFile({ contents: Cypress.Buffer.from(`latitude,longitude,${column}\n52,13,Alpha\n53,14,Beta\n`), fileName: name, mimeType: 'text/csv' }, { force: true })
      cy.contains('button', 'Upload', { matchCase: true }).last().click()
      cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    }
    cy.visit('/')
    cy.get('body', { timeout: 30000 }).should(body => {
      expect(body.find('#dekart-create-report').length || body.text().includes('Ready to connect')).to.be.ok
    }).then(body => {
      if (body.text().includes('Ready to connect')) cy.contains('button', 'Use file upload').click()
      else cy.get('#dekart-create-report').click()
    })
    upload('stations.csv', 'operator')
    cy.get('[data-testid="widgets-tab"]').then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.get('[aria-label="Report widgets"] select').should('not.exist')
    cy.contains('Matching rows').should('not.exist')
    cy.get('button[aria-label="Open panel settings"]', { timeout: 60000 }).should('have.length', 1)
    cy.get('#dekart-report-page-tabs button[aria-label="Add tab"]').first().click()
    upload('sites.csv', 'region')
    cy.contains('button', 'Add widget').click()
    cy.get('#widget-source').select('sites.csv')
    cy.contains('button', 'Category').click()
    cy.contains('[role="combobox"]', 'Select column').click()
    cy.contains('[role="option"]', 'region').click()
    cy.contains('button', /^Create$/).click()
    cy.get('[data-testid="dataset-widgets"]').should('have.length', 2)
    cy.get('[data-testid="dataset-widgets"]').first().should('contain.text', 'stations.csv')
    cy.get('[data-testid="dataset-widgets"]').last().should('contain.text', 'sites.csv')
    cy.get('button[aria-label="Open panel settings"]').should('have.length', 2)
    cy.get('[data-testid="dataset-widgets"]').first().find('g[aria-label="bar"][data-index="1"] rect').first().click()
    cy.get('[data-testid="dataset-widgets"]').first().should('contain.text', 'Clear filters')
    cy.get('[data-testid="dataset-widgets"]').last().should('not.contain.text', 'Clear filters')
    cy.get('#dekart-save-button').click()
    cy.get('#dekart-save-button [aria-label="cloud"]', { timeout: 20000 }).should('be.visible')
    cy.reload()
    cy.contains('Ready', { timeout: 120000 }).should('be.visible')
    cy.get('[data-testid="widgets-tab"]').then(button => { if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click() })
    cy.get('button[aria-label="Open panel settings"]', { timeout: 60000 }).should('have.length', 2)
    cy.get('[data-testid="dataset-widgets"]').first().should('contain.text', 'Clear filters')
    cy.get('button[aria-label="Open panel settings"]').last().click()
    cy.get('[data-testid="widget-settings"]').should('contain.text', 'sites.csv')
    cy.get('[data-testid="widget-settings"]').should('not.contain.text', 'd_')
    cy.get('#widget-settings-source').select('stations.csv')
    cy.get('[data-testid="widget-settings"] [role="combobox"]').contains('Select').click()
    cy.contains('[role="option"]', 'operator').click()
    cy.contains('button', 'Back to widgets').click()
    cy.get('[data-testid="dataset-widgets"]').first().find('button[aria-label="Open panel settings"]').should('have.length', 2)
    cy.get('[data-testid="dataset-widgets"]').last().find('button[aria-label="Open panel settings"]').should('not.exist')
    cy.get('[data-testid="dataset-widgets"]').first().find('g[aria-label="bar"][data-index="1"]', { timeout: 30000 }).should('have.length', 2).last().find('rect').should('have.length.at.least', 1)
    cy.screenshot('report-wide-widgets')
  })
})
