name: 🐞 Bug
description: Report a bug or an issue you've found with Dekart
title: "[Bug] <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is this a new bug in Dekart?
      description: >
        In other words, is this an error, flaw, failure or fault in our software?

        If this is a request for help with using Dekart or querying data more efficiently, please join our [Dekart Community Slack](https://join.slack.com/t/dekartcommunity/shared_invite/zt-1oiygohg1-Wxzugs5y9NliJtSPO8XEoA) or open a [Discussion question](https://github.com/dekart-xyz/dekart/discussions).

        Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues, and I could not find an existing issue for this bug
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        If applicable, log output to help explain your problem.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Dekart version**: 0.13.0
          - **Browser**: Google Chrome
      value: |
        - OS:
        - Dekart version:
        - Browser:
      render: markdown
    validations:
      required: false
  - type: dropdown
    id: database
    attributes:
      label: Which database adapter are you using with dekart?
      description: If the bug is specific to the database or adapter, please add the label 'database adapter'
      multiple: true
      options:
        - BigQuery
        - Athena
        - Snowflake
        - CSV
        - GeoJSON
        - other (mention it in "Additional Context")
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
