/* global cy, describe, it, Cypress, expect */

function uploadCsv (name, rows, addDataset = false) {
  if (addDataset) cy.get('.ant-tabs-nav-add:visible').last().click()
  cy.contains('button', 'Upload File', { timeout: 30000 }).click()
  cy.get('input[type="file"]').selectFile({
    contents: Cypress.Buffer.from(`latitude,longitude,category,amount\n${rows.join('\n')}\n`),
    fileName: name,
    mimeType: 'text/csv'
  }, { force: true })
  cy.contains('button', /^Upload$/).click()
  cy.contains('Ready', { timeout: 120000 }).should('be.visible')
}

function openWidgets () {
  cy.get('[data-testid="widgets-tab"]', { timeout: 120000 }).then(button => {
    if (button.attr('aria-expanded') !== 'true') cy.wrap(button).click()
  })
}

describe('Widget cross filtering', () => {
  it('saves a Search cross-filter setting on leaving edit mode after adding two queries', () => {
    cy.viewport(1280, 960)
    const email = `widget-cross-save-${Date.now()}@example.com`
    cy.setDevClaimsEmail(email)
    cy.intercept(`${Cypress.env('DEKART_E2E_API_URL')}/api/v1/**`, request => { request.headers['X-Dekart-Claim-Email'] = email })
    cy.visit('/')
    cy.ensureTestWorkspace()
    cy.get('#dekart-create-report').click()
    cy.contains('button', 'DuckDB', { timeout: 30000 }).click()
    cy.enterQuery("SELECT concat('BER-', i::VARCHAR) AS locker_id, CASE WHEN i < 2 THEN 'North' ELSE 'South' END AS locker_name, i * 10 AS cells_served, 52.1 + i / 10 AS latitude, 13.1 + i / 10 AS longitude FROM range(3) t(i)")
    cy.get('#dekart-query-execute-button').should('be.enabled').click()
    cy.get('#dekart-query-status-message', { timeout: 120000 }).should('contain', 'Ready')
    cy.get('[data-testid="number-value"]', { timeout: 180000 }).should('have.text', '3')
    cy.get('.ant-tabs-nav-add:visible').last().click()
    cy.contains('button', 'DuckDB', { timeout: 30000 }).click()
    cy.enterQuery("SELECT concat('BER-', i::VARCHAR) AS locker_id, CASE WHEN i = 0 THEN 'North' ELSE 'South' END AS locker_name, (i + 1) * 5 AS buildings, 53.1 + i / 10 AS latitude, 14.1 + i / 10 AS longitude FROM range(2) t(i)")
    cy.get('#dekart-query-execute-button').should('be.enabled').click()
    cy.get('#dekart-query-status-message', { timeout: 120000 }).should('contain', 'Ready')
    openWidgets()
    cy.get('[data-testid="number-value"]', { timeout: 180000 }).should('have.length', 2)
    cy.get('.ant-tabs-tab:visible').first().click()
    openWidgets()
    cy.contains('button', 'Add chart').click()
    cy.contains('button', /^Search/).click()
    cy.get('button[role="combobox"]').last().click()
    cy.contains('[role="option"]', 'locker_id').click()
    cy.contains('button', /^Create$/).click()
    cy.get('[data-testid="search-widget"]', { timeout: 30000 }).should('contain.text', 'Enter a value')
    cy.get('[data-testid="search-widget"]').closest('[data-testid="widget-item"]').find('button[aria-label="Chart actions"]').click()
    cy.contains('[role="menuitem"]', 'Edit chart').click()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').check()
    cy.get('[data-testid="cross-filter-setting"]').should('contain.text', 'Matches:')
    cy.contains('.ant-select', 'Editing').click()
    cy.contains('.ant-select-item-option-content', 'Viewing').click()
    cy.contains('.ant-select', 'Viewing', { timeout: 60000 }).should('be.visible')
    cy.reload()
    cy.contains('.ant-select', 'Viewing').click()
    cy.contains('.ant-select-item-option-content', 'Editing').click()
    openWidgets()
    cy.get('[data-testid="search-widget"]', { timeout: 120000 }).closest('[data-testid="widget-item"]').find('button[aria-label="Chart actions"]').click()
    cy.contains('[role="menuitem"]', 'Edit chart').click()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').should('be.checked')
  })

  it('filters another dataset only after a local opt-in and releases it on clear', () => {
    cy.viewport(1280, 960)
    const email = `widget-cross-filter-${Date.now()}@example.com`
    cy.setDevClaimsEmail(email)
    cy.intercept(`${Cypress.env('DEKART_E2E_API_URL')}/api/v1/**`, request => { request.headers['X-Dekart-Claim-Email'] = email })
    cy.visit('/')
    cy.ensureTestWorkspace()
    cy.get('#dekart-create-report').click()
    uploadCsv('cross-a.csv', ['52.1,13.1,North,10', '52.2,13.2,North,20', '52.3,13.3,South,30'])
    cy.get('[data-testid="number-value"]', { timeout: 180000 }).should('have.text', '3')
    openWidgets()
    cy.get('[data-testid="category-chart"]', { timeout: 120000 }).first().closest('[data-testid="widget-item"]').find('button[aria-label="Chart actions"]').click()
    cy.contains('[role="menuitem"]', 'Edit chart').click()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').check()
    cy.get('[data-testid="cross-filter-setting"]').should('contain.text', 'No matching datasets')
    cy.contains('button', 'Back to charts').click()
    cy.get('[data-testid="category-chart"]').first().find('g[aria-label="rule"][data-index="4"] line', { timeout: 30000 }).first().click()
    cy.get('[data-testid="filter-strip"]').should('contain.text', 'category').and('not.contain.text', '2 datasets')
    uploadCsv('cross-b.csv', ['53.1,14.1,North,5', '53.2,14.2,North,15', '53.3,14.3,South,25'], true)
    openWidgets()
    cy.get('[data-testid="number-value"]', { timeout: 180000 }).should('have.length', 2)
    cy.get('[data-testid="filter-strip"]').should('contain.text', '2 datasets')
    cy.get('[data-testid="filter-strip"] button[title]').should('have.attr', 'title').and('include', 'cross-b.csv')
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).eq(1).should('have.text', '2')
    cy.get('[data-testid="category-chart"]').first().closest('[data-testid="widget-item"]').find('button[aria-label="Chart actions"]').click()
    cy.contains('[role="menuitem"]', 'Edit chart').click()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').uncheck()
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).eq(1).should('have.text', '3')
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').check()
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).eq(1).should('have.text', '2')
    cy.contains('button', 'Back to charts').click()
    cy.contains('button', 'Clear all').click()
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).eq(1).should('have.text', '3')
    cy.get('[data-testid="category-chart"]').first().find('g[aria-label="rule"][data-index="4"] line').first().click()
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).eq(1).should('have.text', '2')
    cy.get('.ant-tabs-tab-remove:visible').last().click()
    cy.contains('button', 'Delete Dataset').click()
    cy.contains('.ant-modal-confirm', 'Remove dataset from map?').within(() => cy.contains('button', 'Yes').click())
    cy.contains('Dataset removed', { timeout: 30000 }).should('be.visible')
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).should('have.length', 1).and('have.text', '2')
    cy.get('[data-testid="filter-strip"]').should('contain.text', 'category').and('not.contain.text', '2 datasets')
  })

  it('locks chart editing while its query fails and restores the selection after recovery', () => {
    cy.viewport(1280, 960)
    const email = `widget-cross-recovery-${Date.now()}@example.com`
    const query = "SELECT 52.1 + i / 10 AS latitude, 13.1 + i / 10 AS longitude, CASE WHEN i < 2 THEN 'North' ELSE 'South' END AS category FROM range(3) t(i)"
    let ownerId
    const openOwnerSettings = () => {
      cy.then(() => cy.get(`[data-widget-id="${ownerId}"]`, { timeout: 30000 }).find('button[aria-label="Chart actions"]').click())
      cy.contains('[role="menuitem"]', 'Edit chart').click()
    }
    cy.setDevClaimsEmail(email)
    cy.intercept(`${Cypress.env('DEKART_E2E_API_URL')}/api/v1/**`, request => { request.headers['X-Dekart-Claim-Email'] = email })
    cy.visit('/')
    cy.ensureTestWorkspace()
    cy.get('#dekart-create-report').click()
    cy.contains('button', 'DuckDB', { timeout: 30000 }).click()
    cy.enterQuery(query)
    cy.get('#dekart-query-execute-button').should('be.enabled').click()
    cy.get('#dekart-query-status-message', { timeout: 120000 }).should('contain', 'Ready')
    cy.get('[data-testid="number-value"]', { timeout: 180000 }).should('have.text', '3')
    uploadCsv('cross-receiver.csv', ['53.1,14.1,North,5', '53.2,14.2,North,15', '53.3,14.3,South,25'], true)
    openWidgets()
    cy.get('[data-testid="number-value"]', { timeout: 180000 }).should('have.length', 2)
    cy.get('[data-testid="category-chart"]').closest('[data-testid="widget-item"]').not('[data-widget-source="cross-receiver.csv"]').invoke('attr', 'data-widget-id').then(id => { ownerId = id })
    openOwnerSettings()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').check()
    cy.contains('button', 'Back to charts').click()
    cy.then(() => cy.get(`[data-widget-id="${ownerId}"]`).find('g[aria-label="rule"][data-index="4"] line').first().click())
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).eq(1).should('have.text', '2')
    openOwnerSettings()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').should('be.checked')
    cy.contains('button', 'Back to charts').click()
    cy.get('#dekart-save-button').click()
    cy.get('button#dekart-save-button .anticon-cloud', { timeout: 60000 }).should('exist')
    cy.reload()
    openWidgets()
    cy.then(() => cy.get(`[data-widget-id="${ownerId}"]`, { timeout: 120000 }).find('button[aria-label="Chart actions"]').click())
    cy.contains('[role="menuitem"]', 'Edit chart').click()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').should('be.checked')
    cy.contains('button', 'Back to charts').click()

    cy.get('.ant-tabs-tab:visible').first().click()
    cy.enterQuery('SELECT * FROM missing_cross_filter_owner')
    cy.get('#dekart-query-execute-button').should('be.enabled').click()
    cy.get('#dekart-query-status-message', { timeout: 120000 }).should('contain', 'Error')
    openWidgets()
    cy.then(() => cy.get(`[data-widget-id="${ownerId}"]`).find('button[aria-label="Chart actions"]').click())
    cy.contains('[role="menuitem"]', 'Edit chart').should('have.attr', 'data-disabled')
    cy.contains('[role="menuitem"]', 'Delete chart').should('have.attr', 'data-disabled')
    cy.get('body').type('{esc}')
    cy.get('.ant-tabs-tab:visible').first().click()
    cy.enterQuery(query)
    cy.get('#dekart-query-execute-button').should('be.enabled').click()
    cy.get('#dekart-query-status-message', { timeout: 120000 }).should('contain', 'Ready')
    openWidgets()
    cy.get('[data-testid="number-value"]', { timeout: 120000 }).eq(1).should('have.text', '2')
    openOwnerSettings()
    cy.get('[data-testid="cross-filter-setting"] input[type="checkbox"]').should('be.checked')
    cy.contains('button', 'Back to charts').click()
    cy.then(() => cy.get(`[data-widget-id="${ownerId}"]`).find('button[aria-label="Chart actions"]').click())
    cy.contains('[role="menuitem"]', 'Delete chart').click()
    cy.get('[data-testid="filter-strip"]').should('contain.text', 'No filters')
    cy.get('[data-testid="number-value"]', { timeout: 30000 }).last().should('have.text', '3')

  })
})
