name: changes

on:
  workflow_call:
    outputs:
      js:
        description: 'Run JS tests'
        value: ${{ jobs.changes.outputs.js }}
      go:
        description: 'Run Go tests'
        value: ${{ jobs.changes.outputs.go }}
      e2e:
        description: 'Run E2E tests'
        value: ${{ jobs.changes.outputs.e2e }}
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      js: ${{ steps.filter.outputs.js }}
      go: ${{ steps.filter.outputs.go }}
      e2e: ${{ steps.filter.outputs.e2e }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
            js:
              - 'public/**'
              - 'src/client/**'
              - 'src/index.js'
              - 'src/setupTests.js'
              - 'src/proto/**'
              - 'package.json'
              - 'package-lock.json'
            go:
              - 'src/server/**'
              - 'src/proto/**'
              - 'go.mod'
              - 'go.sum'
              - 'migrations/**'
            e2e:
              - 'public/**'
              - 'cypress/**'
              - 'cypress.config.js'
              - 'package.json'
              - 'package-lock.json'
              - 'src/**'
              - 'go.mod'
              - 'go.sum'
              - '.github/workflows/e2e.yaml'
              - 'migrations/**'
              - 'Dockerfile'
