name: Detect flavour (premium / oss)

on:
  workflow_call:
    outputs:
      target:
        description: "premium • oss"
        value: ${{ jobs.detect.outputs.target }}
      is_premium:
        description: "true when target == premium"
        value: ${{ jobs.detect.outputs.is_premium }}
      is_oss:
        description: "true when target == oss"
        value: ${{ jobs.detect.outputs.is_oss }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      target:     ${{ steps.set.outputs.target }}
      is_premium: ${{ steps.set.outputs.is_premium }}
      is_oss:     ${{ steps.set.outputs.is_oss }}
    steps:
      - id: set
        run: |
          REPO='${{ github.repository }}'   # owner/name
          if [[ "$REPO" == *dekart-premium ]]; then
            TARGET=premium
          else
            TARGET=oss                      # default → open‑source repo
          fi

          echo "target=$TARGET" >>"$GITHUB_OUTPUT"
          [[ $TARGET == premium ]] && echo "is_premium=true"  >>"$GITHUB_OUTPUT" || echo "is_premium=false"  >>"$GITHUB_OUTPUT"
          [[ $TARGET == oss     ]] && echo "is_oss=true"      >>"$GITHUB_OUTPUT" || echo "is_oss=false"      >>"$GITHUB_OUTPUT"
